# Generated by Django 6.0.4 on 2026-05-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_delete_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_recurring_instance',
            field=models.BooleanField(default=False, help_text='True if this is part of a recurring series'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='When to stop creating recurring appointments', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurrence_frequency_months',
            field=models.PositiveIntegerField(default=3, help_text='Number of months between recurring appointments (e.g., 3 for quarterly, 6 for semi-annual, 12 for annual)'),
        ),
    ]
